name: GitHub CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REPO_NAME: ${{ github.repository }}
  EVENT_NAME: ${{ github.event_name }}

jobs:
  ubuntu:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04
    steps:
      - uses: actions/checkout@v2
      - name: Test
        shell: bash
        run: |
          apt update
          apt-get install -y python3
          python3 --version
