name: GitHub CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  macos:
    name: Test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          sudo TEST_ENV="test_env" bash -e ./code.sh
