name: GitHub CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Windows
        shell: pwsh
        run: |
          python3 -m pip install wheel
          python3 -m pip install localstack
          $env:SERVICES = 's3'; localstack start