name: GitHub CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REPO_NAME: ${{ github.repository }}
  EVENT_NAME: ${{ github.event_name }}

jobs:
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.1.2"
      - run: sudo apt-get install libcurl4-openssl-dev
      - run: sudo apt-get install -y libmagick++-dev
      - run: Rscript  packages.r
      - run: Rscript  PCA.r
